### ISSUE TITLE
Fountains are broken

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#58] opened 2015-06-07 21:41 UTC
This happened after VAO merge.

**Comment by cochrane** [comment] 2015-06-08 07:13
What fountains? Broken how?

**Comment by cochrane** [comment] 2015-06-08 07:20
Sorry for terse comments, writing on phone

**Comment by Lwmte** [comment] 2015-06-08 08:41
I think vvs- means UV-rotated fountain meshes in TR4 and TR5, like ones in Angkor Wat and Streets of Rome. I can confirm they don't work anymore (as well as other UVRotate textures, but they stopped working much earlier than recent VAO code merging).

**Comment by cochrane** [comment] 2015-06-08 09:36
I see. That is probably related to #47 then, because I now use the same animated texture code in both places. Have to see whether fixing that other issue solved this.

**Comment by cochrane** [comment] 2015-06-08 09:37
Both places = for transparent and normal textures.

**Comment by vvs-** [comment] 2015-06-09 00:19
Actually, all animated textures are broken now. Even water textures in TR3-4 now look wrong and checkered.

**Comment by vvs-** [comment] 2015-06-09 22:28
Much better after f80a84c618583451c3fa4b02b0cd8c0453958849.

**Comment by vvs-** [comment] 2015-06-21 12:00
Did anyone noticed the difference between classic animated textures and UV-rotated ones? The former has only one texture and the latter supposed to have two. Just a thought.

**Comment by cochrane** [comment] 2015-06-21 18:50
I did some preliminary investigations, but at the moment I still have no clue what's going. My first idea was a that the animation state for UVrotate was generated after ten VBos had already been generated, but switching that around dint seem to work. I think I need to do more work to h.nderstwnd the data flow while loading levels.

**Comment by Lwmte** [comment] 2015-08-07 20:12
Related to #17, so closing this.

**Closed by Lwmte** 2015-08-07 20:12 UTC
Labels: Bug, Engine, Graphics
