### ISSUE TITLE
OpenTomb [win32-2015-06-25] crashing on startup 

### ISSUE THREAD

**Issue by creative15** [opentomb/OpenTomb#97] opened 2015-06-26 12:05 UTC
message : 
InitSDLVideo: wrong AA sample number, using 0VBOs not supported.

this application has requested runtime to terminate in an unusual way.

on windows XP sp 3
celeron 1.8 GHz ; RAM : 1 GB ; DirectX 9 / OpenGL 2 [highest]

Tried to compile OpenTomb-win32-2015-06-25 source myself the debug version size 56.9 mb
and the release version 4.17 and none of them ran without the pthreadGC1.dll though both ended up 
with the same runtime error.

**Comment by Lwmte** [comment] 2015-06-26 12:14
Try to reduce antialias_samples parameter in config file, seems default antialiasing doesn't work for you (although it should be bypassed in this case... strange).

What's your PC video system?

**Comment by vvs-** [comment] 2015-06-26 12:18
The bypass is buggy. It should set `antialias = 0` but it sets `antialias_samples = 0` instead which doesn't work.

**Comment by Lwmte** [comment] 2015-06-26 12:43
I tried to fix that by setting antialias = 0 in case GL returns zero possible antialias samples, but the problem is, seems that max. number of samples returned by OpenGL is incorrect - I get 32 on my PC, but it crashes, cause actual max. value is 16.

Also, I get "VBOs not supported" error, if antialias samples number is incorrect. Mostly it's because GL extension string is not filled when there is a problem with AA init.

**Comment by creative15** [comment] 2015-06-26 13:15
setting
 antialias = 0 
 antialias_samples = 0
still crashing , so running from command prompt it says "shaders not supported"

I compiled my source without the [libpthreadGC2.dll.a] ; [libmm32.a library] . I guess that might be a problem [even though i got opentomb output]

**Comment by creative15** [comment] 2015-06-26 13:19
My video device is Intel G31/G33 Express chipset
chip type : intel GMA 3100
DAC type: internal
approx. total memory : 384
Monitor: SamSung SyncMaster 550s

**Comment by vvs-** [comment] 2015-06-26 14:50
I have GMA3000 working on Linux with `antialias=0`. Try updating your drivers.

**Comment by creative15** [comment] 2015-06-27 09:45
i have the latest drivers ; may be i need to change some lines in the source code ?? I have downloaded all the tomb raider modding tools [are working fine]  except OpenTomb!!! Plz help!!

**Comment by vvs-** [comment] 2015-06-27 10:16
The original Tomb Raider engine is different as are the unofficial modding tools.

Unfortunately I don't see what else you can do. It seems like a driver issue. Are you drivers from the OEM or from Intel? If you didn't do so already try to download latest drivers from Intel website.

**Comment by Lwmte** [comment] 2015-06-27 11:29
I think we must arrange system requirements section with mentioning that OpenTomb needs *at least* OpenGL 2.1 support.

**Comment by creative15** [comment] 2015-07-04 05:06
Sorry , I made a mistake too, the OpenGL driver version is 1.4

**Comment by Lwmte** [comment] 2015-08-07 19:59
I think we may close this now, as unfortunately, engine can't support OpenGL lower than (at least) 2.1 anymore, and lower than 3.2 in near perspective.

**Closed by Lwmte** 2015-08-07 19:59 UTC
Labels: 3 - Done, Crash
