### ISSUE TITLE
Fallback state implementation and unused speeds

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#28] opened 2015-05-14 22:28 UTC
Copied from Tomb Raider forums (post by Joey79100):

> When there's a pit behind you, and you press Backwards, Lara will start hoping backwards. Once she's above the empty, she starts falling, playing animation 34 and then 35 (that have StateID 3, that is used for jumping forwards), but it's wrong. She should play animation 93 that has StateID 29 (and without animation 34 before).  
> This animation and its StateID were considered as unused by Fluen when creating his animation list (and consequently, StateID29 wasn't referenced in the StateID list), because visually it looks the same as animation 35, but actually it is used, and there's a reason.  
> The problem that exists now is that if you are already pressing the Action key when jumping backwards (to grab the ledge), Lara gets stuck on the edge, switching continuously between animation 22 (starts falling while jumping forward when she hasn't finished the "jump cycle" (when there was a ceiling)), and animation 82 (falls on the ground).  
> Animation 93 lets you grab a ledge only after 7 frames (not a hardcoded thing, the StateID change is written this way in the animation), while animation 35 lets you do this during the whole animation. So using animation 93 will prevent her from being stuck like she currently does.
> 
> Proof that the StateID exists: in TOMB.MAP that was leaked with the May TR1's demo, it's referenced this way:

`0001:00013da0  lara_as_fallback_`

> (StateID 30 is used when shimmying left, and is just after 29 which has a rather clear name)  
> I don't know if you've written code for this StateID though, but there shouldn't be a lot of differences.  
> By the way it seems that the speed for animation 95 (ready to grab) is ignored. She's meant to go forward, but in OpenTomb she has no horizontal speed.  
> The speed she has when she hits a wall while jumping are ignored too.

**Comment by Joey79100** [comment] 2015-06-22 08:46
Much better now, but animations 34/35 are still played when after sliding backwards, and it causes Lara to make... weird things.

**Comment by Lwmte** [comment] 2015-08-05 17:32
Speeds are not fixed, though.

**Comment by Gh0stblade** [comment] 2015-08-07 17:41
The speeds are completely broken, I've been comparing things to the original Tomb Raider engine in an attempt to fix the problems. I have an almost *i think* working solution but it breaks on TR3 sprinting and for some reason the speeds are still not being applied correctly (on the roll state) it has to be something deeper than just issues with calculating the speed/accel values.

I've also noticed Lara's speed is not updated quickly enough after slowing the game down? Could be wrong though. I'll try fix this.

**Comment by Gh0stblade** [comment] 2015-08-07 20:23
Ok, I pushed a variant of the experimental code here:

https://github.com/Gh0stblade/OpenTomb/commits/Lara_Tests_2

Now, this improves the calculation (acceleration/deceleration) on a per frame basis. Anyhow, you should notice that pressing back will resolve the issue causing Lara to fall off. That issue was caused because the previous code didn't decelerate  Lara's speed and because it's fixed she'll go too far off the edge.

There are some weird problems though, for example run animation seems a little too slow. If you stand still and jump up Lara has the speed applied yet she doesn't appear to move (like in the original games) or it's a very small amount she's moving to the point it's not noticeable. I think the root cause to the speed/movement issues is not only caused by the floor slants affecting result positions but also the base calculations seem to be incorrect? Another example is, rolling will perfectly work, but if you roll again Lara isn't reaching the wall which is odd.

Any ideas?

**Comment by Gh0stblade** [comment] 2015-08-09 02:39
Some *good* and *bad* news on this should be posted tomorrow. Some nice progress on my end *i think* (well the calculations say so) I have to recalculate some other things and compare to the original game :)

**Comment by vvs-** [comment] 2015-08-09 15:47
Actually, I'm not convinced that the horizontal speed in animation 95 shouldn't be ignored. If you try a standing jump then it should be obvious that the distance is the same. But when there is a ledge then it's a different story.

**Closed** 2017-10-31 13:45 UTC
Labels: 2 - Working, Game Logic, Unimplemented
