### ISSUE TITLE
Random crashes related to collision

### ISSUE THREAD

**Issue by Lwmte** [opentomb/OpenTomb#227] opened 2015-07-27 18:09 UTC
I already mentioned in #174 that I got random crash when capturing a video with slide error. Just before this, Lara stucked at sector border in slide state.

Now I got another funny error. I was testing one-shot switches in TEMPLE.TR2 (level 2 in TR3), and went to that long dark room with key and switch which activated spiky wall, but right after I pulled a switch and started running to get a key, Lara suddenly stopped as if she stumbled into a wall (however, nothing was in front of her), and few seconds later, engine crashed.

In both cases, I didn't get enough time to turn on debug drawer to check what's wrong, but I suppose it's not collision, but some state control memory corruption bug.

**Comment by stohrendorf** [comment] 2015-07-28 04:11
If you're running in Windows, maybe the Windows event log catched the error with the "OOOOOOPS" exception message I put in for checking the validity of the the EngineContainer...

**Comment by Lwmte** [comment] 2015-07-28 11:12
I saw that funny line in source, but so far never encountered such message in logs/error reports...

**Comment by stohrendorf** [comment] 2015-08-04 11:50
Are there still crashes?

**Comment by Lwmte** [comment] 2015-08-08 20:34
Yes, recently I got one in WALL.TR2 again. No "OOOOOPS" message in command window.

**Comment by Lwmte** [comment] 2015-08-08 20:34
It's possibly not related to collision, as this time it happened during noclip.

**Comment by Gh0stBlade** [comment] 2017-08-14 13:15
Going to close this one, I assume it was initially caused by the old refactored branch. If this still happens feel free to reopen.

**Closed by Gh0stBlade** 2017-08-14 13:15 UTC
Labels: Collision, Crash, Game Logic
