### ISSUE TITLE
Wrong lever behavior

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#33] opened 2015-05-17 22:23 UTC
In *St. Francis' folly* lever 66 can be operated only once, while in the original it's unlimited. That leads to possible deadlock if player didn't trigger closing a door when entered the room first time.

**Comment by Lwmte** [comment] 2015-05-18 09:39
I noticed that when testing this particular switch setup. Strange thing is that in original level, switch trigger for switch 66 is actually set as one-shot, which leads me to a confusion, because one-shot state flag SHOULD indeed lock the switch after first use.

So either it is hardcoded override (as with TR2 spinning blades sound override in Great Wall), or TR1 switches are processed a bit differently and won't lock up on first use. Actually, I remember something like that, I was able to un-pull certain one-shot switches in TR1.

Just another headache, thanks to Core Design.

**Comment by vvs-** [comment] 2015-05-18 12:15
That gave me an idea: why not implement a run-time patching for original levels? I've seen other bugs in them as well, so it's the only way to fix them all. Some other FLOSS engines already do just that, if I'm not mistaken that's *Exult*.

**Comment by Gh0stblade** [comment] 2015-05-18 12:55
I thought LUA scripts could override triggers already?

**Comment by vvs-** [comment] 2015-05-18 13:01
Yes, they could by they don't at this time.

**Comment by Lwmte** [comment] 2015-05-18 13:04
I should add an option to print out all auto-generated trigger functions, and then an option to override certain trigger function with user-specified one. I just afraid that if it's common option in TR1 to have one-shot switches work two-way, it's better to make automated as well.

**Comment by vvs-** [comment] 2015-05-18 13:45
Or you could patch a trigger even before generating Lua code like static meshes.

**Comment by vvs-** [comment] 2015-05-29 19:19
It might or might not be related. In *The Cistern* room 10, switch 11 works only once too. It can be pulled multiple times, but only the first one flips the rooms outside. So, you can fill these rooms with water, but can't flush it.

**Comment by vvs-** [comment] 2015-06-27 21:51
I think the entity `lock` has incorrect behavior. Right now it locks the entity and prevents updates to its' mask. Actually, it should lock the trigger from changing its' state again and not the entity properties.

Right now it prevents *Temple of the Cat* from being completed. Any one of the two triggers locks the entity and prevents another trigger from activating it.

**Comment by Lwmte** [comment] 2015-06-27 22:07
The problem is, original TRs have *no such thing* as trigger state. That is, every time you step onto trigger, it is executed again and again. Only entities have lock state assigned to them. So basically, when trigger is set as *one-shot*, it basically means that any entity which was activated using this trigger, won't be activated again, ever.

It's just TR1 which presumably has different trigger/entity processing, and we still need to understand the difference.

**Comment by vvs-** [comment] 2015-06-27 22:27
I can imagine such scenario: when trigger is activated it sets the entity mask and after deactivating it resets it back, only when the lock is set it doesn't reset the mask. I don't know if this makes sense as I'm not familiar with all possible cases.

**Comment by vvs-** [comment] 2015-06-29 16:24
With this patch it works just like in the original. But I haven't tested any other cases yet.
```
diff --git a/scripts/entity/entity_functions.lua b/scripts/entity/entity_functions.lua
index a39f0c7..d712fd7 100644
--- a/scripts/entity/entity_functions.lua
+++ b/scripts/entity/entity_functions.lua
@@ -53,7 +53,9 @@ function door_init(id)   -- NORMAL doors only!
     setEntityActivity(object_id, 1);
     
     entity_funcs[id].onActivate = function(object_id, activator_id)
-        swapEntityState(object_id, 0, 1);
+	if(getEntityLock(object_id) == 0 or getEntityState(object_id) == 0) then
+            swapEntityState(object_id, 0, 1);
+	end;
     end;
     
     entity_funcs[id].onDeactivate = entity_funcs[id].onActivate;    -- Same function.
@@ -1366,4 +1368,4 @@ function baddie_init(id)    -- INVALID!
         if(getEntityActivity(object_id) == 0) then enableEntity(object_id) end;
     end;
     
-end
\ No newline at end of file
+end
diff --git a/scripts/entity/script_switch.lua b/scripts/entity/script_switch.lua
index d301281..9631b4a 100644
--- a/scripts/entity/script_switch.lua
+++ b/scripts/entity/script_switch.lua
@@ -364,7 +364,7 @@ function switch_activate(object_id, actor_id)   -- actor ID is needed to activat
             end
             return true;
         end);
-    elseif(off.ready_anim == t and getEntityLock(object_id) ~= 1) then  -- Locked switches doesn't flip back!
+    elseif(off.ready_anim == t) then
         setEntityAnim(object_id, off.trig_anim, 0);
         setEntityAnim(actor_id, off.actor_anim, 0);
         --setEntityActivity(object_id, 1);
diff --git a/scripts/trigger/trigger_functions.lua b/scripts/trigger/trigger_functions.lua
index 0bf0694..a7e4df0 100644
--- a/scripts/trigger/trigger_functions.lua
+++ b/scripts/trigger/trigger_functions.lua
@@ -58,8 +58,7 @@ function activateEntity(object_id, activator_id, trigger_mask, trigger_op, trigg
     
     -- Ignore activation, if activity lock is set.
     
-    if(lock == 1) then return end;   -- No action if object is locked.
-    lock = trigger_lock;             -- Update object lock.
+--    if(lock == 1) then return end;   -- No action if object is locked.
     
     -- Apply trigger mask to entity mask.
 
@@ -82,6 +81,7 @@ function activateEntity(object_id, activator_id, trigger_mask, trigger_op, trigg
     
     -- Update trigger layout.
     
+    lock = trigger_lock;             -- Update object lock.
     setEntityTriggerLayout(object_id, mask, event, lock);
     setEntityTimer(object_id, trigger_timer);                   -- Engage timer.
 end;
@@ -183,4 +183,4 @@ end
 function playCutscene(cutscene_index)
     if(getLevelVersion() < TR_IV) then return 0 end;
     print("CUTSCENE: index = " .. cutscene_index);
-end
\ No newline at end of file
+end
diff --git a/src/resource.cpp b/src/resource.cpp
index 795a357..8070429 100644
--- a/src/resource.cpp
+++ b/src/resource.cpp
@@ -987,7 +987,7 @@ int TR_Sector_TranslateFloorData(room_sector_p sector, class VT_Level *tr)
                                             if(action_type == TR_ACTIONTYPE_SWITCH)
                                             {
                                                 // Switch action type case.
-                                                snprintf(buf, 256, " if((switch_state == 0) and (switch_sectorstatus == 1)) then \n   setEntitySectorStatus(%d, 0); \n   setEntityTimer(%d, %d); \n", operands, operands, timer_field);
+                                                snprintf(buf, 256, " if(switch_sectorstatus == 1) then \n   setEntitySectorStatus(%d, 0); \n   setEntityTimer(%d, %d); \n", operands, operands, timer_field);
                                                 if(only_once)
                                                 {
                                                     // Just lock out activator, no anti-action needed.
```

**Comment by vvs-** [comment] 2015-07-20 21:44
BTW, while the recent changes to triggers fixed *Temple of the Cat*, the switch 66 is still locked and doesn't work more than once.

**Comment by Lwmte** [comment] 2015-07-20 22:17
Usually you don't need to specify "locking" behaviour for entities, you only have to ignore `onDeactivate` method, then they wouldn't deactivate at all. As for TR1 switches, I believe that additional condition must be added to switch script function, so it will ignore lock flag for that particular game version.

**Comment by vvs-** [comment] 2015-07-20 22:25
> additional condition must be added to switch script function, so it will ignore lock flag for that particular game version

Yep.

**Comment by vvs-** [comment] 2015-07-21 20:02
A secret in *Temple of the Cat* depends on this issue.

**Comment by vvs-** [comment] 2015-07-28 11:18
First of all, seems that there are state, mask, flags and timer which are all changed independently. Triggers change mask, flags and timer but not state which is changed by entity. After each state change have occurred entity compares new state and mask and starts new animation.

In the original engine if mask has changed during animation it triggers new animation right after changing state. In OpenTomb it ends up in an unexpected thing: the triggers change their function! The antitrigger become trigger and vice versa.

Also, in the original engine triggers compute a new mask and only when all conditions are met the lock is set. The current entity state should be active, new mask should be 0x1F and the triggers' lock flag should be set. In OpenTomb the lock flag is set first and only when conditions are met the entity is locked. That means that in the original engine you can change entity state even after activating trigger with lock flag set until all the conditions are met. In OpenTomb you can deactivate the entity only once.

The timer is behaving strangely and I'm still not sure what's going on. Looks like it affect the switch and the entity differently.

Could you create another test levels where there will be triggers or antitriggers behind both switches?

**Comment by Lwmte** [comment] 2015-07-28 11:31
True - mask is set by trigger, but state is changed by trigger as well. Here is the proof (decompiled TR1 *TestTriggers* function snippet):

`           if ( (resulting_mask & 0x3E00) == 0x3E00 )    // 11111 - mask is set
          {
            if ( trigger_layout & 0x100 )
              *(_WORD *)v48 = resulting_mask | 0x100;   // Extract trigger one-shot flag
            if ( !(*(_BYTE *)(v47 + v55 + 68) & 1) )    // Check entity one-shot flag
            {
              v52[0] = *(_BYTE *)(v47 + v55 + 68);
              v65 = v15;
              v49 = v47 + v55 + 68;
              if ( (*(_BYTE **)((char *)&objects_ptr + v13 - 2475560))[52 * *(_WORD *)(v47 + v55 + 12) + 48] & 2 )
              {
                if ( ((v52[0] >> 1) & 3) == 3 )     // Entity type?
                {
                  *(_DWORD *)(v47 + v55 + 4) = 0;
                  v41 = v16;
                  v64 = v13;
                  v42 = EnableBaddieAI(v16, 0) == 0;
                  v43 = *(_BYTE *)v49;
                  if ( v42 )
                    v44 = v43 | 6;
                  else
                    v44 = v43 & 0xF9 | 2;
                  *(_BYTE *)v49 = v44;
                  AddActiveItem(v41);
                }
                else if ( !((v52[0] >> 1) & 3) )
                {
                  *(_DWORD *)(v47 + v55 + 4) = 0;
                  *(_BYTE *)v49 = v52[0] & 0xF9 | 2;
                  v45 = v16;
                  AddActiveItem(v16);
                  EnableBaddieAI(v45, 1);
                }
              }
              else
              {
                *(_DWORD *)(v47 + v55 + 4) = 0;
                *(_BYTE *)v49 = v52[0] & 0xF9 | 2;
                AddActiveItem(v16);
              }
              goto LABEL_96;
            }
          } `

**Comment by vvs-** [comment] 2015-07-28 11:33
Then how could you explain that when the mask is changed during the animation the entity starts new animation even when no trigger is active?

**Comment by Lwmte** [comment] 2015-07-28 11:43
You checked it with doors? It's probably true, maybe some entities check their masks in their subroutines to *deactivate* themselves, but not activate. However, it doesn't make sense, as the only way to change entity activation mask is trigger.

Also, antitrigger can't become trigger and vice versa, cause *only* way to activate antitrigger (i. e. `deactivateEntity` trigger script routine) is to explicitly call antitrigger function.

Indeed, trigger state is inversed when activation was done, i.e. next *successful* call to `activateEntity` will effectlvely produce deactivation. The thing is, *successful* call means that activation mask is changed - e.g. if you call two similar triggers with 0x1F mask in a row, second will be discarded.

**Comment by vvs-** [comment] 2015-07-28 12:05
I checked it with your test level. And the door is activating and deactivating by itself when no triggers are active.

It's you who called the blue sector an antitrigger and it's indeed a `deactivateEntity` trigger. And the triggers never change their action in the original TR. They always behave in the same way: the blue one is always deactivates the door and the next one is always activates it. If you activate both triggers during an animation then the next state change occurs only after completing the animation. But in OpenTomb if you change the mask during an animation they start working in the opposite way: the blue trigger is now activating the door and the next one is deactivating it.

**Comment by vvs-** [comment] 2015-07-28 12:22
There could be a confusion here. I'm describing my tests with *both* the original TR1 and OpenTomb. And all the tests were made using the special LEVEL1.PHD with four triggers and a door.

**Comment by stohrendorf** [comment] 2015-07-28 12:35
Can you put that level file into the rository, say in folder `tests/tr1` with a `LEVEL1.md` or `.txt` describing the test case and the expected results?

**Comment by Lwmte** [comment] 2015-07-28 12:50
You mean door opens right after level loading? This is normal behaviour, and that's what I call *pre-activated entity*. Technically, door *is not* checking its mask on start-up, it's just start-up initialization that happens in `InitialiseItem` routine in original. If entity is pre-activated, disabled and enabled states are inversed. Best example is grated door leading to Qualopec tomb.

Only entities which check its own activation mask (at least in TR1) is switch and cabin (not clear what's the purpose, just did a quick search through decompiled source).

**Comment by vvs-** [comment] 2015-07-28 13:04
No. The doors are opening and closing by itself after I activate several triggers during animation sequence and then quickly jump out of that sectors. The animation is finished and only then the door starts new animation. There are no active triggers at that moment already.

**Comment by Lwmte** [comment] 2015-07-28 13:07
@stohrendorf I have uploaded test level with description into `/tests` directory! :wink:

**Comment by vvs-** [comment] 2015-07-28 13:07
> or .txt describing the test case and the expected results?

I'm already trying to describe it here but still without success :smile:

**Comment by Lwmte** [comment] 2015-07-28 13:09
Ah, you mean that if you quickly run over two different triggers (e.g. trigger and antitrigger), then both actions are performed in TR1, and second action is ignored in OpenTomb? This is completely different case, which is yet to be solved.

**Comment by vvs-** [comment] 2015-07-28 13:10
Yes. And even worse, it's not only ignored but results in triggers changing their action to the opposite.

**Comment by vvs-** [comment] 2015-07-28 13:31
But I was talking about *two* bugs in the current trigger implementation. The second one is directly affecting one-shot triggers. In the original engine triggers set the entity lock flag only *after* all conditions are met. That means that the current OpenTomb implementation is broken.

**Comment by Lwmte** [comment] 2015-07-28 13:44
Yes, once I had lock flag setting *inside* activation condition, but eventually after lots of revisions it was moved above. I will move it back in, but before that we must be sure it acts same way in TR2-5. And I already know it works differently in TR3, as lock flag is set even with non-complementary triggers (i.e. if I step onto trigger with mask 00011 and lock flag set, and then step onto trigger with mask 11100, entity won't be activated).

**Comment by Lwmte** [comment] 2015-07-28 13:46
As for first bug, I believe it's more related to particular *onActivate / onDeactivate* entity implementation.

**Comment by vvs-** [comment] 2015-07-28 13:49
To test that hypothesis we need a different test levels. It's a pity that we can't make such things using only an FOSS. The Windows requirement is a no go for me.

**Comment by vvs-** [comment] 2015-07-28 17:14
Looks like a timer is applied to the entity only after it's locked, otherwise it's applied only to a switch. Also, in that case the door changed state the second time only when the trigger sector is touched again.

**Comment by vvs-** [comment] 2015-07-28 17:21
For triggers the entity is considered deactivated when it's in initial state, even when it's not zero.

**Comment by Lwmte** [comment] 2015-07-30 18:01
Please check if behaviour is correct or not! Unfortunately, door entity function got MUCH MORE complicated than it was, especially initialization process... I hope that it's only kind of entity which requires such complicated setup.

**Comment by vvs-** [comment] 2015-07-30 18:45
It's almost correct. You've fixed the bug with trigger skipping which changed its' action to the opposite. But the lock is behaving incorrectly. The the trigger still sets the lock flag before all conditions are met. The door state can only be changed once even if some conditions are not true.

**Comment by Lwmte** [comment] 2015-07-30 18:51
That's actually the way lock flag behaves in TR4. However, I can't understand why it affects actual item activation. The way it happens is, lock flag indeed is set by ANY trigger, but it shouldn't affect further trigger activation, because lock flag is compared against activation mask, and if it's not set, execution of trigger continues.

**Comment by vvs-** [comment] 2015-07-30 19:20
But in TR1/2 the activation mask could change *even* if it was changed by the locked trigger. Until *all* the conditions are true the entity is still not locked. So, you can deactivate the entity with a locked trigger and it still doesn't set its' lock. You can then activate and deactivate the entity with non-locked triggers as long as you wish. This isn't how it works in OpenTomb now.

**Comment by vvs-** [comment] 2016-06-23 10:42
Likewise, regression and need new scripts.

**Closed** 2016-07-31 10:03 UTC
Labels: Bug, Game Logic, Lua
