### ISSUE TITLE
Savegame Structure Idea

### ISSUE THREAD

**Issue by TokyoSU** [opentomb/OpenTomb#433] opened 2017-04-17 12:07 UTC
## The First Save is Lara:

0. LaraCurrentBarPercentage (Health, Speed, Air, Damage, Cold)

1. PositionXYZ:
- LaraPosX;
- LaraPosY;
- LaraPosZ;

2. OrientationXYZ:
- OrgX;
- OrgY;
- OrgZ;

3. RoomNumber:
- LaraRoom; // Int ?

(Room have maxNumber ?) in room editor is 99 can be extends to 199 but not more ?.

4. StateIDCurrent & Next:
if Lara is in water and reload a save is ground lara is bugged ? need to save it ?
-StateIDC;
-StateIDN;

5. LaraHoldingWeapon:
Function or Boolean ?
Need to Check all Weapon ?
-CurrentWeaponHold; ?

6. LaraCurrentTarget:
if lara target a mobs need to save (no bug) ?
Check if Lara have weapon hold ? if true no need to save it !
-CurrentLaraTarget(SlotID (Index in Room Editor or in Slot ?), CordX, CordY, CordZ, Room);

7. LaraCurrentRoomIndex:
Check the particularity of Room (With StateID) (Only one Function to Save?):
In Water ?
In Sand ?
In Lava ? (custom index ?) (new room ?) if lara go dead with anim like spikes ?
In WaterRapid (TR3)
Other...

8. LaraCurrentAnimation & Store Actual SpeedHorizontal & SpeedVertical ?
- LaraCurrentAnimation;
- SpeedH;
- SpeedV;

## The Other Save Is Enemy:
-Similar to Lara but no with Weapon (Exept BADDY?)
-Need to Save Actual MeshSwap ?
-LastHP;
-Animation;
-StateIDC & StateIDN;
Etc...

## The Other Save is Sprites (Like FLAME, Bubbles (if spawned))
Current Pos of Sprites (Mesh Moving ?) / So need to Save Mesh Pos ?

## The Other Save is Trap, Door, Switch (ON/OFF)
-The StateIDCurrent (OPEN or CLOSE)
-The Animation ID
-If Blocked or Not Triggered ?

## Need to Store Current Position of Item in Map (No PickedUp);
XYZ, OrientY (no need X, Z)
If Already PickedUp no store it ?

## Current Inventory Objects:
- Weapon;
- NumberAmmo;
- Timer; (The Time you have played ?)
- medikit_Number; (Small & Big) in one function ?
- NumberOfSecret;
- DistanceTraveled;
- CurrentLevel; (First saved or in the 6 ?)
- NameOfLevel(Like TR1->TR3 Save)

The Files Name is SAVEGAME_0.DAT ?
generated like this ?
i + 1 ? (i = currentSave if exist generated other number) or just save in the files (replace) ?
Selected in game !

## So the GameSaveFormat should like this:
Example:

// Generated by Game (TOMB1, 13:57 2017/04/17)
// Savegame No0
LaraCurrentBarHealth: 800 (Basically lara have 1000 HP)
LaraCurrentBarAir: 1800 (Default if not in Water Room)
LaraCurrentBarDamage: 1000 (Default (HPBar)
LaraCurrentBarCold: 1000 (Default (HPBar)
LaraCurrentBarSpeed: 700 (Default ?)
LaraCordX: 1205480
LaraCordY: 504808
LaraCordZ: 1205480 (Exact of X ?)
LaraOrgX: -34000
LaraOrgY: 0
LaraOrgZ: 34000
LaraRoom: 34
LaraCurrentStateID: 0
LaraNextStateID: 0 (Standing no Movement) (Or Key Pressed during Save)
LaraHoldingWeapon:True, IS_PISTOLS
LaraCurrentTarget:8 (WOLF), 1205340, 504808, 1205340, 34 (No WOLF is in save or in DEBUG function)
LaraCurrentRoomIndex:IS_NORMAL (no water just ... ground) (IS_WATER, IS_SAND etc...)
LaraCurrentAnimation:103 (Standing)
LaraCurrentSpeedH: 0
LaraCurrentSpeedV: 0
WolfCordX:
etc..

Files is Crypted ?
If Anyone have Idea to Savegame Structure can be speak here.
Sorry for bad english i'm french.

**Comment by vvs-** [comment] 2017-04-17 13:04
Actually, current save game file is a script without any ordering. It is executed to restore the game state. What could be benefits of a strictly ordered DSL like this? It would require a parser and a lot of temporary variables. And this presumed that there could be consumers of that format besides the game engine. And engine already allows players to modify anything at run-time using debugging console.

**Comment by TokyoSU** [comment] 2017-04-17 13:40
I hesitate to take badly what you say,
You have a savegame function i dont view it or read it 👍 .
But for now it's just a suggest, no needed,
I have Windows so cant be load sources, exemple here: 
[https://github.com/opentomb/OpenTomb/issues/430](url)
And for now you have just Lara Working (HardCollision, World, Inventory (Just Item (No Other Function like Select)) No GUI (Just LoadScreen with bar and Strings in inventory), Pickup Item, and a sorry for language but "An hp bar that looks like nothing", Sorry sorry...
## Basically you need (to upgrade or fix):
- Rewrite code for Windows (94% of PC work with Windows, not Linux).
- Title Level to work, and with a good GUI (Select a level Fast (with Diary or Not)).
- Inventory with Background Image and Objects animated if selected.
- A Script Files (Like SCRIPT and ENGLISH with TRLE to Customize Strings and Level).
- [Fix] Shaders, the light is too powerful (the light max is 1.00 in editor).
- [Delete] Ragdoll not needed in TR level.
- [Fix] Collision of Lara (With Wall).
And for me it's hardcoded (LUA).

it's not a order but suggest.
you complicate your life with load_level commands or other.
PS: And need a EXE or Option to change "KEY" Region (i have a FRENCH_KEYBOARD)

**Comment by vvs-** [comment] 2017-04-17 16:12
It's really hard to understand what are you saying.

Game is not finished so there are non implemented functionality and bugs. This surely will be fixed eventually.

There is no such thing as "code for Windows". Everything is cross-platform and can be compiled and ran on Windows, Linux and macOS.

When I said "ordered DSL" I meant that you are suggesting a Domain Specific Language with _statements_ that has been arranged. That's a mathematical term that I meant here, not a demand.

**Comment by TokyoSU** [comment] 2017-04-17 16:30
Sorry for bad english, I'm french.

Ok, but basically,
if you start to create a game (Source Code And other) you start with UI (Like Title and Options) ?
And if you want a "copy" of TR with "no hardcoded" enemie, you need this structure (no my structure but similar)

**Comment by vvs-** [comment] 2017-04-17 17:06
There is no inherent connection between UI and everything else. Right now everything is possible to do by using embedded LUA scripting. That's a temporary shortcoming which should be addressed eventually. Right now the engine is in alpha stage which means that it's meant as a technical preview for computer savvy people.

There are no hardcoded enemies or other objects. Everything is scripted in LUA. There are no plans to replicate a Core Design's engine internals. Only functional compatibility was intended. Not even UI will be necessarily similar. There are no plans to make it easy to change the game behavior for people totally unfamiliar with computer programming either.

**Comment by TeslaRus** [comment] 2017-04-17 17:45
Game engine is a big and complex project; here does not works logic "do what I like and when I like". The engine architecture must be planned, and features implementation order must be planned (Steve McConnell "Code Complete"). LUA using for config, game logic and saves is a good architecture unification (same logic was usen in ID tec engines). Engine code was written for posix standard and may be compiled under MSW (MinGW or CYGWIN), Linux, MAC. Some people compile engine under VS - it is their choose, and I understood them, but make whole project MSW only buildable is not ethical.

**Comment by zdimension** [comment] 2017-04-18 12:51
If it helps you, you can post in French, then I'll translate it in English.

**Comment by TokyoSU** [comment] 2017-04-18 18:14
Ok thanks 😉

2017-04-18 14:51 GMT+02:00 Monsieur Z <notifications@github.com>:

**Closed** 2017-09-10 06:35 UTC
