### ISSUE TITLE
Lara clip through walls when pulling Underwater Switches.

### ISSUE THREAD

**Issue by Gh0stBlade** [opentomb/OpenTomb#342] opened 2016-06-26 10:56 UTC
I have tested this on both the underwater switches in the City of Vilcabamba level. When pulled,Lara is teleported through the wall mesh.Most likely related to Lara position correction.

**Comment by vvs-** [comment] 2016-06-26 11:04
Yes, that's a very old bug. Also, there is related bug with pushing/pulling movables in a narrow spaces.

**Comment by vvs-** [comment] 2016-07-10 19:33
Seems like pulling blocks is fixed now. But not the underwater switches.

**Comment by vvs-** [comment] 2016-11-21 13:56
I'm not able to reproduce this after recent changes.

**Comment by TeslaRus** [comment] 2016-12-06 18:37
fixed after introducing moving to trigger activation point

**Comment by vvs-** [comment] 2016-12-06 19:16
I think we should close this.

**Closed by vvs-** 2016-12-06 19:16 UTC
Labels: Bug, Collision
