### ISSUE TITLE
Lara grab on nothing

### ISSUE THREAD

**Issue by Gh0stBlade** [opentomb/OpenTomb#340] opened 2016-06-26 10:39 UTC
Nothing much to say here, this is a very rare bug. I have only reproduced it 3 times. This rarely occurs when jumping and grabbing towards the bear stable in City of Vilcabamba.

http://i.imgur.com/xS4JKW5.png

**Comment by vvs-** [comment] 2016-06-26 10:52
I've seen the same in _Natla's Mines_, it's perfectly reproducable. I'll post a test case here later.

**Comment by TeslaRus** [comment] 2016-08-02 18:57
I found the bug reason (stable reproduce in setgamef(1, 5) room 21: x = 39305, y = 41164, z = -15360): it is from check climbability function (near wall case): I will fix it after frame system fixing / rewriting.

**Comment by vvs-** [comment] 2016-08-02 19:05
The climbability test is very buggy indeed. I'm getting lots of incorrect animations using action+up, some of which include geometry penetration when coming out of water and dramatic frame rate drop in _Caves_ room 35.

**Comment by TeslaRus** [comment] 2016-08-07 07:49
Probably fixed in https://github.com/opentomb/OpenTomb/commit/c96d58a5c2633f535c2f4b4630a75805c1eacd8c

**Comment by vvs-** [comment] 2016-11-27 20:32
I just had another instance of this bug but can't reproduce it. Also, the game just froze after I tried to make a screenshot. Seems that Bullet can produce incorrect results in rare cases. And it might be affected by compiler optimization level too.

**Comment by vvs-** [comment] 2017-09-07 15:11
Happens in the beginning of _The Cistern_ and in _Natla's Mines_. Also, it's affected by other activities, e.g. by issuing `r_coll` on console, but can be reproduced again later.
![untitled](https://user-images.githubusercontent.com/5171934/30170398-b89295e6-93f7-11e7-85ab-bf9e8215c6ed.png)

**Comment by TeslaRus** [comment] 2017-09-08 07:41
float has bad precision here (bad algorithm stability)

**Comment by TeslaRus** [comment] 2017-10-01 12:54
can't reproduce... try latest build (after gui_refactoring merging - in one algorithm float was replaced by double)

**Comment by vvs-** [comment] 2017-10-01 13:59
_Natla's Mines_ isn't reproducible anymore, but _The Cistern_ still is. Try to hop backwards, then roll and press ACTION to grab the ledge:
![untitled](https://user-images.githubusercontent.com/5171934/31055326-d9ec71be-a6c9-11e7-93db-8a71fb46b66f.png)

**Comment by TeslaRus** [comment] 2017-10-01 15:51
yep, reproduced with locked fps = 60

**Comment by vvs-** [comment] 2017-10-01 16:04
Also, it's still reproducible in _Natla's Mines_, just occasionally.

**Comment by TeslaRus** [comment] 2017-10-01 16:56
added extra conditions in https://github.com/opentomb/OpenTomb/commit/1ef2d9638590547bc08314aa20cd305ed97bbf8d
roll to grab is unstable (may be not hang, but no more air hang)

**Comment by vvs-** [comment] 2017-10-01 18:57
Yes. I've noticed that some state control code doesn't respect animation sequence, so that the state change could happen at the wrong animation frame.

**Comment by vvs-** [comment] 2017-10-01 19:38
Ok. Formally, the original bug is fixed. And precision and animation issues have their own issues.

**Comment by vvs-** [comment] 2017-10-05 17:21
This bug is reared its ugly head again. This time in _The Great Wall_. `setEntityPos(20,58424,33767,-3055,90,0,0)` and press and hold action+up until Lara slides back and hangs on air.

**Comment by TeslaRus** [comment] 2017-10-06 20:36
hmmm... 2 more checks for from vertical down check and one more for max delta z angle... thanks... + slide vas broken...

**Closed** 2017-10-07 13:25 UTC
Labels: Bug
