### ISSUE TITLE
Weak floor in Caves doesn't fall deep enough

### ISSUE THREAD

**Issue by stohrendorf** [opentomb/OpenTomb#237] opened 2015-08-03 01:26 UTC
See here: 
![opentomb-breakable-floor](https://cloud.githubusercontent.com/assets/7853507/9029209/5b883294-398f-11e5-8e31-f063ed47607d.png)

**Comment by vvs-** [comment] 2015-08-03 12:50
I can't reproduce it:
![screenshot from 2015-08-03 15 49 15](https://cloud.githubusercontent.com/assets/5171934/9037784/3ea76bbe-39f7-11e5-9a36-e966d4bdd4b2.png)

**Comment by stohrendorf** [comment] 2015-08-03 13:12
Looking at the FPS, maybe it's a timing issue.

**Comment by vvs-** [comment] 2015-08-03 14:12
Simulating 51 Hz didn't help. May be it's a Bullet issue? Could you try bulletphysics/bullet3@1fa4819afc806cd8a7081cd48943fc9d0c25bb92? Also, optimization for OpenTomb should be `-O0`.

**Comment by stohrendorf** [comment] 2015-08-03 14:23
This is a MSVC Debug build, so no optimization at all; otherwise I'd have a few hundred FPS ;)

Is there something special about that bullet version compared to 2.83.5?

**Comment by vvs-** [comment] 2015-08-03 14:34
Yes, I use it for my testing and it works :smile: I can't say the same thing about any other version.

Actually, optimization level shouldn't affect GPU performance. Only Bullet depends on CPU.

**Comment by stohrendorf** [comment] 2015-08-03 14:51
The thing is that OpenTomb is single-threaded, and MSVC does some heavy checks in debug builds (e.g. checking that iterators are valid by checking if they belong to the same container when compared, that the iterated container didn't change, that the iterator isn't outside the bounds, etc.). This means that CPU indeed has a great impact, as the GPU needs to wait for it.

**Comment by vvs-** [comment] 2015-08-03 15:01
I'd say that these checks are *very* heavy then if their impact is by the order of magnitude. And it still looks like a Bullet is affecting the whole performance.

**Comment by stohrendorf** [comment] 2015-08-03 15:08
Yes, these checks *are* heavy, but they are very useful when debugging (e.g. iterating over a container and resizing it in the iteration, which for example led to the fix in e0201499d063766dcf4d89b9d3b439d852b49726, where `m_self->room->containers` was actually changed inside the loop while iterating over it).

And I have read several forum posts about the scaling of bullet, e.g. one should try to keep the scale at 1 meter equals 1 floating point unit, not about 1000 (or 512?) like in OpenTomb, as other scales *might* lead to performance and stability issues, yet I don't think that this scale is the root of the problem here.

**Comment by Gh0stblade** [comment] 2016-06-22 11:02
I cannot reproduce this at both high and low framerates. If this still persists, please reopen this issue. I will close it for now.

**Closed by Gh0stblade** 2016-06-22 11:02 UTC
Labels: Bug, Question
