### ISSUE TITLE
Model view is inconsistent

### ISSUE THREAD

**Issue by vvs-** [opentomb/OpenTomb#140] opened 2015-07-08 16:18 UTC
I see a different model_view and model_view_projection on old and new engines.

**Comment by stohrendorf** [comment] 2015-07-08 19:12
It seems like I wrongly assumed that the btMatrix3x3-array-operator gives access to columns, yet it gives access to rows, which means that every piece of code using that effectively operates on the transposed matrices. I'm trying to fix this.

**Comment by stohrendorf** [comment] 2015-07-09 06:29
... and worse, I just found out that the btMatrix3x3 doesn't have a fourth row as it is needed for proper calculations. (My fault, I don't know why I ignored the obvious 3x3 in the name!)

**Comment by vvs-** [comment] 2015-07-09 10:13
I'd say that all mistakes so far occurred in translation of vector math to Bullet.

**Comment by stohrendorf** [comment] 2015-07-09 10:15
I fully agree. I'm currently evaluating if GLM is a better choice for all the rendering and transformation purposes, as it is far more suited to deal with linear math.

**Comment by cochrane** [comment] 2015-07-09 10:36
I'm currently working on fixing this. Give me until today evening…

**Comment by cochrane** [comment] 2015-07-09 13:16
Resolved in 2def93d in the macfix-luastate branch (or was it luastate-macfix?), which also means rendering works again now. Sort of. That branch also includes some stuff to get the whole thing working on Mac OS X again, which will cause trouble with other systems. I have plans to remove that later-ish and replace it with a solution that actually works well. Though probably not today. If you feel up to it, you're free to try merging these changes into your branch, and then removing the Mac-specific build weirdness. Until then I'm leaving this open.

This has revealed a whole lot of other fun issues: Entities aren't drawn, the camera isn't hooked up to Lara, texture coordinates are wrong, positions of static meshes are wrong, frustums are wrong, frustums crash because std::vector does not ensure proper alignment for btScalar3 (at least on my platform), alpha test doesn't work (that one is my fault) and other fun stuff. Someone should make individual tickets for them.

On the code side: I changed a bit about how shaders are managed to reflect actual ownership rules, and documented that in code. The net effect is a reduction in overall code size. I also went from OpenGL 4.4 (sadly not supported by my graphics card) to OpenGL 3.2 Core Profile, which contains everything we need and then some and is the baseline for all modern graphics work. This change is the reason why the alpha test is broken (this feature is deprecated and must be replicated via shaders. Not hard, I just didn't get around to it yet. If you feel like it:
    
    if (color.a < 0.5) discard;

I also added a different maths library (well, two files) specifically for graphics matrices. This is one I wrote and used everywhere, so it contains some stuff not necessary here. I only used it where it was really required. In the medium term, it may be useful to think about what maths library to use where.

**Comment by Lwmte** [comment] 2015-07-09 14:32
@cochrane Regarding alpha test, is it possible to fix #18 with shader? I mean, only apply alpha test shader for textures with attribute of 1?

**Comment by cochrane** [comment] 2015-07-09 14:36
Good point. Yes, that should be possible. I have to think about the best way to do it (basically we could either split all meshes into ethe part that uses alpha test and the part that doesn't, or we add a new vertex attribute and decide per face).

**Comment by Lwmte** [comment] 2015-07-09 14:46
You mean copying texture attribute into vertex attribute? Good idea, but there could be problems with animated textures, as theoretically level builder can create animated sequence with both opaque and transparent textures (and even alpha-blended ones). However, it's not officially supported feature, as TRLE doesn't allow to create animated textures with different texture attributes, it was only possible in Dxtre3d.

**Comment by cochrane** [comment] 2015-07-09 15:36
Actually, that would be even easier through that; I just have to update that flag along with the texture coordinates.

**Comment by vvs-** [comment] 2015-07-09 16:00
> This has revealed a whole lot of other fun issues: Entities aren't drawn,

They are drawn correctly.

> texture coordinates are wrong,

That's because of #124.

> positions of static meshes are wrong,

They seems to be correct.

> frustums are wrong,

That's because of #137.

Most of the problems you described are from using `luastate` branch. There are much less problems on `master`.

> I also went from OpenGL 4.4 (sadly not supported by my graphics card) to OpenGL 3.2 Core Profile, which contains everything we need and then some and is the baseline for all modern graphics work.

That's a bad idea. We actually targeting OpenGL 2 and OpenGL ES 2. I reverted this change on my branch. That also fixed alpha.

**Comment by cochrane** [comment] 2015-07-09 16:43
> Most of the problems you described are from using luastate branch. There are much less problems on master.

Well, what branch am I supposed to use? I don't really care either way, but this is getting confusing.

**Comment by vvs-** [comment] 2015-07-09 17:01
Yes, I agree. I'm not complaining, just pointing that out.

I'm in process to setup my own branch for those who want to test your changes without much hassle.

**Comment by vvs-** [comment] 2015-07-09 17:09
Ok. It now lives in `render` branch in my forked repository. I removed all LuaState related stuff there but kept cochranes' Mac OSX fixes (or at least I think so). You can check it out.

**Comment by vvs-** [comment] 2015-07-09 17:53
To get most of it you should workaround #137 somehow. I've patched it locally to always return true. This is not included in that branch as it's not a proper fix. I've reverted texture atlas so #124 doesn't apply here.

Also, some entities are drawn but not all.

**Comment by stohrendorf** [comment] 2015-07-09 17:53
By the way, why is OpenGL **2** the target? That's horribly old.

**Comment by vvs-** [comment] 2015-07-09 17:55
Because there are many people who doesn't have support for higher version yet (me included). That's temporary until this improves. Also, no open source driver exist which support something higher than OpenGL 3.3.

**Comment by stohrendorf** [comment] 2015-07-09 18:03
Interesting, because OpenTomb already uses OpenGL functionality that's standard in OpenGL 3+, and most OpenGL debuggers can't even deal with pre-3.x code anymore (this is why I bumped the version initially a bit too far). I understand that it's not the right thing to assume that everyone has a OpenGL 4.4-compatible graphicscard with 4GB GPU mem and 32 GB main memory, yet I think it's also wrong to target such a very old standard. And some of the things OpenTomb uses aren't even supported in the compatibility profile any more here. Targeting, say, version 3.2 is much more sane in my opinion.

**Comment by cochrane** [comment] 2015-07-09 18:12
Okay, I'll downgrade to OpenGL 2, but I'll keep VAOs in. If anyone complains about them, I'll add the manual version back in. I very strongly suggest we keep using glew, it makes life considerably easier.

About branch: Well, which branch do you all expect to get merged into master soon(-ish)? My initial instinct is to keep working on (my branch of) luastate because that's the most developed one, but if I'm wrong, that might be a waste of time.

@stohrendorf The only 3+ functionality we use is VAOs, and those are a very widespread extension (plus, they're optional). Other than that, 2 has all the features we need, and we're using it in a way that is mostly compatible with OpenGL 3.2. The main exception to that is the alpha test, but I'll change that one to use shaders now.

I generally agree with you: I'd prefer to stay on 3.2 Core Profile. But this is a change that should be made carefully, when we know how many people are actually impacted.

> And some of the things OpenTomb uses aren't even supported in the compatibility profile any more here.

What do you mean by that exactly? We use one thing that isn't supported by OpenGL 2. The OpenGL 3.2 compatibility profile supports everything the Core Profile does and then some (but the compatibility profile itself isn't available on some platforms, where your only choice is 2.1 with extensions or 3.2 or higher core profile.)

**Comment by vvs-** [comment] 2015-07-09 18:13
> most OpenGL debuggers can't even deal with pre-3.x code anymore

May be it's so in commercial software but it's definitely not in open source world.

> And some of the things OpenTomb uses aren't even supported in the compatibility profile any more here

I don't think so. I certainly have only OpenGL 2.1 and GLSL 1.20 and everything works ok.

**Comment by Lwmte** [comment] 2015-07-09 18:14
I won't object upgrading to OpenGL 3.2, after all, we're making kind of "next-gen TR classic" here, but some people may suffer from it, there are folks out there in TR community who still own Pentium 4 class computers.

I will arrange a survey on TRF about this.

**Comment by vvs-** [comment] 2015-07-09 18:15
> About branch: Well, which branch do you all expect to get merged into master soon(-ish)? My initial instinct is to keep working on (my branch of) luastate because that's the most developed one, but if I'm wrong, that might be a waste of time.

I don't have an answer. But I think it's a mistake to base a bug fixes on some branch which isn't even merged yet.

**Comment by vvs-** [comment] 2015-07-09 18:18
> I won't object upgrading to OpenGL 3.2, after all, we're making kind of "next-gen TR classic" here, but some people may suffer from it

Until there are *real* features which required OpenGL > 2 I don't see a point in making such requirements. It'd only make things harder.

**Comment by cochrane** [comment] 2015-07-09 18:36
> I don't have an answer. But I think it's a mistake to base a bug fixes on some branch which isn't even merged yet.

Doing it in main will require me to port at least some of the changes from luastate over. For example, the function pointers aren't set up properly on Mac OS X, and this is a problem that I would like to resolve by simply using glew, as the other branch already does. So my enthusiasm for doing the fixes again on a different branch is very limited. I'll do it if it's actually necessary, though. So far I don't think it is.

**Comment by vvs-** [comment] 2015-07-09 18:40
I've actually kept Glew in my branch. It seems stable and has no relation to other problematic stuff.

**Comment by cochrane** [comment] 2015-07-09 18:43
That's honestly very good. But I hope you'll understand why I'm not going to start working on your branch either right now. Someone with a clearer idea of what is going on should probably pick a branch (might be yours), merge it into master, and then I'll deal with things going on from there.

**Comment by vvs-** [comment] 2015-07-09 18:43
Perhaps we should extract something from `luastate` and merge it into master? I could try it tomorrow. If all goes well I could make a PR.

**Comment by vvs-** [comment] 2015-07-09 21:53
I've just tested latest `luastate` and it's worse than `master`. There are problems not present there like noclip() not working, Lara missing. I don't even have working font.

It can't be merged in a present state. I've created a pull request with just Glew commits. If there is something else missing that you feel is necessary, tell me and I include it in that PR as well.

**Comment by stohrendorf** [comment] 2015-07-10 06:38
Lara *is* there (after calling `noclip()` and `freelook()` in the console). She's just dead, like most of the engine :skull: 
![lara](https://cloud.githubusercontent.com/assets/7853507/8613388/e193e4fa-26de-11e5-9648-24ac425e7a6e.png)

**Comment by vvs-** [comment] 2015-07-10 10:01
Yes, she is. It's just that her position is broken in `luastate`. In `master` she is with the camera. In noclip state she should be in position 0,0,0 but in `luastate` she is not there.

Also, the freelook command is broken. The sequence `noclip()` and `freelook(1)` should position the camera outside in position 0,0,0 and only Lara should remain inside.

**Comment by vvs-** [comment] 2015-07-10 10:10
Just figured out that noclip and freelook initially are in opposite state. When you put `0` in autoexec.lua they  actually assume it's 1.

**Comment by stohrendorf** [comment] 2015-07-10 10:42
part of the problem is that boolean parameters in lua interface functions now expect *real* `true`and `false`, not 0 and 1 any more.

**Comment by vvs-** [comment] 2015-07-10 10:55
Then it should be changed in all places.

**Comment by vvs-** [comment] 2015-07-10 11:02
BTW, should this issue be closed? The original bug is fixed now.

**Comment by stohrendorf** [comment] 2015-07-10 11:12
It's not in `master` yet. And I fear that the `luastate` branch became actually a fork, so merging selected fixes back could be troublesome.

**Comment by vvs-** [comment] 2015-07-10 11:34
Yes, it's a fork because it's big. But it's constantly improving. Right now it's almost as good as a master (which is broken :wink:). If we keep focusing on fixing bugs instead of introducing new features and changing API, then it will be ready to merge eventually.

I can close that PR with selected features, so we can assume that all fixes will go in `luastate` instead of `master`.

**Comment by stohrendorf** [comment] 2015-07-11 16:52
Merged, so I'm closing this.

**Comment by vvs-** [comment] 2015-07-13 12:22
We were too quick to close this. It does *not* fixed. I compared matrices for entities and they are way different.

**Comment by vvs-** [comment] 2015-07-13 13:01
It's the math that got broken everywhere in the process of translating to Bullet and then to Matrix4 with intermediate changes in between. I'm sure that fixing the math will take care of almost all bugs introduced by the code refactoring.

**Comment by Lwmte** [comment] 2015-07-13 13:28
I'm currently trying to understand where it got broken - either on resource loading (vt level -> OpenTomb level in resource.cpp) or in runtime (entity::frame function and so on).

Is it correct to use btTransform instead of raw 4x4 OpenGL matrix at all? I remember Bullet had special functions to convert btTransform to OpenGL matrix and back, maybe ignoring this is the reason for all rendering bugs? Correct me if I'm wrong.

**Comment by vvs-** [comment] 2015-07-13 13:38
I checked VBOs and they contain correct data (vertices, normals, colors, texture coordinates and indices), so resource loading should be out of question. That's on my patched branch. On `master` texture coordinates are wrong, of course.

**Comment by vvs-** [comment] 2015-07-13 13:41
Render::renderSkeletalModel has wrong model_view and model_view_projection matrices.

**Comment by Lwmte** [comment] 2015-07-13 13:44
It's not only rendering problem. Seems Lara is infinitely sent to freefall state (and eventually dies) because her mesh positions are wrong, which results in wrong collision detection. So I believe problem occurs somewhere earlier.

**Comment by vvs-** [comment] 2015-07-13 13:46
Yes, I'm not saying that it's in that function. The matrices are calculated earlier in the code.

**Comment by vvs-** [comment] 2015-07-13 13:49
> Is it correct to use btTransform instead of raw 4x4 OpenGL matrix at all?

The answer was [here](https://github.com/opentomb/OpenTomb/issues/117#issuecomment-119900745). But I thought that cochrane already fixed that.

**Comment by vvs-** [comment] 2015-07-13 13:50
BTW stohrendorf already changed some geometry structures in 351ad5274e01f848a282cbeb88e51be9ee138239.

**Comment by stohrendorf** [comment] 2015-07-13 13:55
I was careful with that not changing existing logic, but under the assumption that the existing code was correct.

**Comment by Lwmte** [comment] 2015-07-13 13:55
But it's not related to matrixes, only to planes/normals/etc.
Probably Cochrane fixed this in some of his forks, but anyway, it was never merged into luastate/master. Sincerely, I've lost the track of all branches/forks which were present at some time in the past two weeks, but now removed.

**Comment by Lwmte** [comment] 2015-07-13 13:56
I guess, if it *was* working before, it was correct.

**Comment by vvs-** [comment] 2015-07-13 13:57
> it was never merged into luastate/master

No, everything was merged. You should not worry about that.

> under the assumption that the existing code was correct.

If it worked correctly, then it's correct, isn't it?

**Comment by vvs-** [comment] 2015-07-13 14:01
> But it's not related to matrixes, only to planes/normals/etc.

Planes used 4x4 matrices before, but now they're not. But projections still use 4x4 matrices, so it could be broken, at least in theory.

**Comment by vvs-** [comment] 2015-07-13 16:51
I just want to point out again that entities and static meshes seems to have different problems. There could be a different bug for statics. Entities have their positions and boundary boxes in the correct place, but statics are not.

**Comment by vvs-** [comment] 2015-07-13 17:14
Also, did you notice that collision mesh now always is attached to Laras' model even in noclip mode? And it doesn't have white collision objects.

**Comment by vvs-** [comment] 2015-07-13 17:31
The same is true for all other entities: their boundary boxes and positions are correct, but collision mesh is attached to model which is rendered in incorrect place. But Lara shouldn't even have boundary box in noclip.

**Comment by Lwmte** [comment] 2015-07-13 17:37
Yes, exactly - as kinematic entities derive their physical body dimensions from OpenGL transformation matrix. That's why their positions are wrong in the first place (e.g. switches). Theoretically, dynamic entities should be rendered and positioned correctly, but I can't test it, cause engine crashes on every level switch and with any game version except TR1.

I believe Lara's bodies are attached to her in noclib because some condition was incorrectly modified or removed by mistake. Her collisional objects shouldn't update in noclip.

**Comment by vvs-** [comment] 2015-07-13 17:41
> Seems Lara is infinitely sent to freefall state (and eventually dies)

I guess that's because there are no white collision objects attached to her.

> but I can't test it, cause engine crashes on every level switch

I really suggest that you revert 3639216938f134292b9adf8736293eb436337850 and b3cb74737a542eef011b6ceea8ef62e059b7a267 in your branch. These commits are responsible for crashes that you are experiencing.

**Comment by Lwmte** [comment] 2015-07-13 17:42
Oh, right, I forgot about ghost objects. Seems that they're not generated at all or their code is also messed up.

**Comment by Lwmte** [comment] 2015-07-13 17:43
Honestly, I don't remember what's responsible for room collision checks - ghosts or bodies (possibly both). We have to ask TeslaRus about this.

**Comment by vvs-** [comment] 2015-07-13 17:44
If TeslaRus will look at the code I think he could fix it in no time. You should already notice that C++ isn't that different if you have used to it.

**Comment by vvs-** [comment] 2015-07-13 18:07
I found that hair is rendered incorrectly and caused crashes. The *Lost Valley* is the only level that crashed here and that's because of a hair which is smeared on the whole picture.

**Comment by Lwmte** [comment] 2015-07-13 18:09
And basically it means that any level with addCharacterHair script command is crashed? This means hair generation is also broken.

**Comment by vvs-** [comment] 2015-07-13 18:21
I think that all the brokenness comes from incorrect matrix manipulation.

Here you can see that angles for these objects are all incorrect:
![screenshot from 2015-07-13 21 18 18](https://cloud.githubusercontent.com/assets/5171934/8657228/02f8cebc-29a5-11e5-8e2b-c94235ed57f5.png)

**Comment by stohrendorf** [comment] 2015-07-13 22:37
I'm planning to buy a book about OpenGL programming tomorrow, hopefully I can avoid such dumb mistakes after reading it :)

**Comment by Lwmte** [comment] 2015-07-14 02:06
Hopefully yes, and hopefully it's the first and the last time we end up in such situation...

**Comment by vvs-** [comment] 2015-07-14 10:10
Never put several unrelated things in the same commit and always test it before committing. Then there will be no such situations again.

**Comment by vvs-** [comment] 2015-07-17 15:51
The problem lies in `Entity::updateCurrentBoneFrame`.

**Comment by vvs-** [comment] 2015-07-17 18:22
Correct me if I'm wrong but Bullet use normalized product in `theta`, while OpenTomb should use non-normalized product in `fi` and normalize the result.

**Comment by vvs-** [comment] 2015-07-17 19:15
This result is then fed directly to OpenGL `mvTransform` and `mvpTransform` matrices in `Render::renderSkeletalModel`.

**Comment by vvs-** [comment] 2015-07-19 12:24
It still may be not fixed. In noclip Laras' model should be in the center of a screen but it's not.

**Comment by vvs-** [comment] 2015-07-19 14:40
It's not fixed. You can see it in inventory and noclip.

**Comment by vvs-** [comment] 2015-07-22 17:06
Ok. What about a pull request? I tested your fixes and they looks good to me.

**Comment by Lwmte** [comment] 2015-07-23 16:04
Fixed in a39c3fd

**Closed by Lwmte** 2015-07-23 16:04 UTC
Labels: bug, Engine, Graphics
